import React, { useState } from 'react';
import { ArrowLeft, X } from 'lucide-react';
import useVerify from '../../hooks/useVerify';
import { getDeviceId } from '../../utils/helper';
import { Spinner } from '../Spinner';

const VerifyCodeModal = ({ onClose, userId, deviceId }) => {

    const [code, setCode] = useState('');



    const { isLoading, verify } = useVerify();
    console.log("deviceid: ", deviceId)



    const handleSubmit = () => {
        const data = {
            userId,
            code,
            deviceId
        }
        verify(data);
    };


    return (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
            <div className="bg-gray-900 text-white rounded-2xl p-6 pb-8 w-[400px] h-[550px] max-w-[90vw] relative">
                <div className="flex items-center justify-between mb-6">
                    <button className="text-white p-1">
                        <ArrowLeft size={24} />
                    </button>
                    <button onClick={onClose} className="text-white p-1">
                        <X size={24} />
                    </button>
                </div>

                <h2 className="text-2xl font-bold mb-4">Verify Authenticator</h2>
                <p className="text-gray-400 mb-6">Enter the 6-digit code generated by the Authenticator App.</p>

                <label className="text-sm font-medium mb-2 block text-white">Authenticator App Code</label>
                <div className="flex items-center border-2 border-yellow-500 rounded-lg px-3 py-3 mb-6 bg-transparent">
                    <input
                        type="text"
                        maxLength={6}
                        value={code}
                        onChange={(e) => setCode(e.target.value)}
                        className="bg-transparent text-white w-full focus:outline-none placeholder-gray-500 text-base"
                        placeholder=""
                    />
                    <button className="text-yellow-300 font-medium ml-2 text-sm hover:text-yellow-300">
                        Paste
                    </button>
                </div>

                <button
                    disabled={code.length !== 6 || isLoading}
                    onClick={handleSubmit}
                    className="w-full bg-amber-300 hover:bg-yellow-400 disabled:bg-yellow-800
                        disabled:opacity-50 text-black py-3 rounded-lg font-medium cursor-pointer 
                        disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
                >
                    {isLoading ? <Spinner size={20} /> : "Submit"}
                </button>


            </div>
        </div>
    );
};

export default VerifyCodeModal;